import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Navigation from './Navigation/Navigation';
import { Container, Div, Section, Wrapper } from './WrapperAdmin.styled';
import { Header } from './Header/Header';
import { useSelector } from 'react-redux';
import { selectRole } from '@/redux/user/selectors';

const WrapperAdmin = ({ children }) => {
  const [activeButtonIndex, setActiveButtonIndex] = useState('admin-panel');
  const [showBurgerMenu, setShowBurgerMenu] = useState(false);
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  const router = useRouter();
  const role = useSelector(selectRole);
  if (role !== 'ADMIN') {
    router.replace('/');
    return;
  }

  const handleButtonClick = (index, route) => {
    setActiveButtonIndex(index);
    router.push(route, undefined, { shallow: true });
  };

  const handleClickBurger = () => {
    setShowBurgerMenu((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>VicTar</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <Wrapper>
        <Container>
          <Header
            handleClickBurger={handleClickBurger}
            showBurgerMenu={showBurgerMenu}
          />
          <Section>
            {windowWidth <= 768 ? (
              showBurgerMenu && (
                <Navigation
                  backdrop={windowWidth <= 768}
                  activeButtonIndex={activeButtonIndex}
                  handleButtonClick={handleButtonClick}
                />
              )
            ) : (
              <Navigation
                backdrop={windowWidth <= 768}
                activeButtonIndex={activeButtonIndex}
                handleButtonClick={handleButtonClick}
              />
            )}
            <Div>{children}</Div>
          </Section>
        </Container>
      </Wrapper>
    </>
  );
};

export default WrapperAdmin;
