import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Navigation from './Navigation/Navigation';
import { Container, Div, Section, Wrapper } from './WrapperAdmin.styled';
import { Header } from './Header/Header';

const WrapperAdmin = ({ children }) => {
  const [activeButtonIndex, setActiveButtonIndex] = useState('admin-panel');
  const router = useRouter();

  const handleButtonClick = (index, route) => {
    setActiveButtonIndex(index);
    router.push(route, undefined, { shallow: true });
  };

  return (
    <>
      <Head>
        <title>VicTar</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <Wrapper>
        <Container>
          <Header />
          <Section>
            <Navigation
              activeButtonIndex={activeButtonIndex}
              handleButtonClick={handleButtonClick}
            />
            <Div>{children}</Div>
          </Section>
        </Container>
      </Wrapper>
    </>
  );
};

export default WrapperAdmin;
