import Head from 'next/head';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';

import { Benefits } from '@/components/Benefits/Benefits';
import { SliderFeedbacks } from '@/components/SliderFeedbacks/SliderFeedbacks';
import { Categories } from '@/components/Categories/Categories';
import { instance } from '@/axios/axiosDefault';
import { getCategories } from '@/redux/products/slice';
import { Slider } from '@/components/Slide/Slider';

export async function getServerSideProps() {
  const response = await instance('/groups/list');
  const data = response.data.groups.slice(0, response.data.groups.length - 1);

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getCategories(data));
  }, [data, dispatch]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      {
        <>
          <Slider />
          <Categories />
          <Benefits />
          <SliderFeedbacks />
        </>
      }
    </>
  );
}
