import Head from 'next/head';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';

import { Benefits } from '@/components/Benefits/Benefits';
import { SliderFeedbacks } from '@/components/SliderFeedbacks/SliderFeedbacks';
import { Categories } from '@/components/Categories/Categories';
import { instance } from '@/axios/axiosDefault';
import { getCategories, getProductsFilter } from '@/redux/products/slice';
import { Slider } from '@/components/Slider/Slider';

// export async function getServerSideProps() {
//   const response = await instance('/groups/list');
//   const data = response.data.groups.slice(0, response.data.groups.length - 1);

//   return {
//     props: { data },
//   };
// }
export async function getServerSideProps() {
  try {
    const response = await instance('/groups/list');
    const data = response.data.groups.slice(0, response.data.groups.length - 1);
    const res = await instance(`/products/list?limit=500`);
    const list = res.data.products;
    return {
      props: { data, list },
    };
  } catch (error) {
    console.error(error);
    return {
      props: { data: [], list: [] },
    };
  }
}

export default function Home({ data, list }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getCategories(data));
    dispatch(getProductsFilter(list));
  }, [data, dispatch, list]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      {
        <>
          <Slider />
          <Categories />
          <Benefits />
          <SliderFeedbacks />
        </>
      }
    </>
  );
}
