import Head from 'next/head';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';

import { Benefits } from '@/components/Benefits/Benefits';
import { SliderFeedbacks } from '@/components/SliderFeedbacks/SliderFeedbacks';
import { Categories } from '@/components/Categories/Categories';
import { instance } from '@/axios/axiosDefault';
import { getCategories } from '@/redux/products/slice';
import { Slider } from '@/components/Slider/Slider';
import { useRouter } from 'next/router';
import { refreshUser } from '@/redux/user/operations';
import { setTokenAccess, setTokenRefresh } from '@/redux/user/slice';

export async function getServerSideProps() {
  try {
    const response = await instance('/groups/list');
    const data = response.data.groups.slice(0, response.data.groups.length - 1);

    return {
      props: { data },
    };
  } catch (error) {
    console.error(error);
    return {
      props: { data: [] },
    };
  }
}

export default function Home({ data }) {
  const dispatch = useDispatch();
  const router = useRouter();

  const { accessToken, refreshToken } = router.query;

  useEffect(() => {
    dispatch(getCategories(data));
  }, [data, dispatch]);

  useEffect(() => {
    if (!accessToken && !refreshToken) {
      return;
    }

    dispatch(setTokenAccess(accessToken));
    dispatch(setTokenRefresh(refreshToken));
    dispatch(refreshUser());
    router.push('/');
  }, [accessToken, dispatch, refreshToken, router]);
  return (
    <>
      <Head>
        <title>VicTar</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>

      {
        <>
          <Slider />
          <Categories />
          <Benefits />
          <SliderFeedbacks />
        </>
      }
    </>
  );
}
